---

- name: Ansible Playbook for Configuring Raspberry Pi Nodes

  hosts: nodes
  remote_user: pi
  become: yes
  vars_files:
    - ./vars/raspi_config.yml
  roles:
    - {role: configurer, tags: ['configure']}
    - {role: installer, tags: ['install']}
