---

- name: Ansible Playbook for Configuring Raspberry Pi Nodes

  hosts: all
  remote_user: pi
  become: yes
  vars_files:
    - ./vars/raspi_config.yml
  roles:
    - {role: configurer, tags: ['configure']}
    - {role: installer, tags: ['install']}

- name: Master nodes only setup

  hosts: masters
  remote_user: pi
  become: yes
  roles:
    - {role: masters, tags: ['masters']}
